project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "HMK"
  favicon: images/favicon-32x32.png
  navbar:
    right:
      - publications.qmd
      - text: Experience
        href: experience/experience.qmd
      # - fun.qmd
      - text: Resume
        href: resumes/HMK_Resume.pdf
  page-footer:
    left: |
      <span text-align="center" class="faux-block">&#169; 2023 Harshith Mohan Kumar CC BY-SA 4.0</span>
    right: |
      <span text-align="center" class="faux-block"><a href="mailto:hiharshith18@gmail.com">Contact Me!</a></span>
      

format:
  html:
    from: markdown+emoji
    theme: sandstone
    css: _sandstone.scss
    toc: true


